In [1]:
#PRIMER PASO: IMPORTAR LIBERIAS

import pandas as pd

In [2]:
#SEGUNDO PASO: IMPORTAR BASE DE DATOS DE ARCHIVO EXCEL
#donde debemos crear una variable en el que se almacenara ducho archivo

basedatos=pd.read_excel(r'C:\Users\garro\OneDrive\Escritorio\DATA SCIENCE\TRABAJO PRACTICO\SalarioPromedio.xlsx', sheet_name='empresas')

In [3]:
#TERCER CASO: VERFICAMOS SI SE REALIZÃ“ LA CARGA A PARTIR DE M0STRAR LOS PRIMEROS CINCO DATOS
#(donde la primer fila son los nombres de las columnas, por lo que se mstraran cuatro filas con datos)

basedatos.head()

,Provincia,id_provincia_indec,Departamento,codigo_departamento_indec,2014-01-01 00:00:00,2014-02-01 00:00:00,2014-03-01 00:00:00,2014-04-01 00:00:00,2014-05-01 00:00:00,2014-06-01 00:00:00,...,2021-08-01 00:00:00,2021-09-01 00:00:00,2021-10-01 00:00:00,2021-11-01 00:00:00,2021-12-01 00:00:00,2022-01-01 00:00:00,2022-02-01 00:00:00,2022-03-01 00:00:00,2022-04-01 00:00:00,2022-05-01 00:00:00
0,Buenos Aires,6,25 de Mayo,6854,7645.463931,7151.668073,7854.263607,8305.806117,7958.287807,11345.013038,...,77798.801973,79104.891299,87532.518297,88431.839702,126845.341493,101149.665899,97753.471113,106230.750039,108933.561643,112323.013288
1,Buenos Aires,6,9 de Julio,6588,8257.999503,8412.811601,8351.786067,9066.448357,8959.567978,12956.134214,...,87586.274670,93178.159067,96877.723091,98721.693757,145071.183034,111573.159347,111574.502824,123224.840282,123032.905792,128275.308632
2,Buenos Aires,6,Adolfo Alsina,6007,7773.443878,7544.805143,7903.290092,8373.707431,8339.203583,11866.668659,...,84613.431352,87535.427033,91830.611866,92784.295682,136560.717637,103833.129362,121553.318527,115866.045931,118064.146399,122624.812582
3,Buenos Aires,6,Adolfo Gonzales Chaves,6014,7941.941135,7613.754899,7816.041641,7989.492005,8254.835262,11387.808570,...,76069.844646,76162.251952,80917.327002,81495.466644,123442.100685,95241.762198,94351.792408,98148.387461,98265.808313,106166.292461
4,Buenos Aires,6,Alberti,6021,9051.689829,9416.442365,8875.519517,9416.707325,9381.836472,13350.438442,...,95364.963826,101161.468413,103392.290726,106936.339409,168167.535029,140701.323143,120860.816291,136122.189733,134975.588847,145257.455355

Este dataset contiene los datos de los salarios en la Argentina desde el 2014 hasta 2022, mes a mes. Presenta los siguientes datos: 
       - nombre de provincia 
       - ID_provincia (valor Ãºnico que se le otorga a cada provincia/CABA) 
       - nombre de departamento 
       - ID_departamente (valor Ãºnico que se le entrega a cada departamento)
       - de la columna 5 a Ãºltima se encuentran los salarios desde el 2014 hasta 2022 
      
  Al momento de realizar un anÃ¡lisis se podrÃ­a hacer una limpieza de datos y poder hacer diferentes tablas relacionando algunos datos para evitar las repeticiones. Por ejemplo: se puede eliminar los datos de los nombres de provincia y generar una segunda tabla que relacione el ID_provincia con su respectivo nombre, como tambien eliminar el nombre del departamento y crear una tercera tabla para relacionar los nombres de departamentos con su respectiva ID. Esto permite reducir que se repitan los datos, y por lo tanto, reducir la memoria. Por lo tanto, los datos mÃ¡s importantes son ID_provincia, ID_departamento y los salarios.